
datasets:
    icsd:
        hypothetical: False
        structures_file: "inputs/structures/icsd_structures.json.gz"
        energies: "inputs/structures/icsd_energies.csv"
    oqmd_unrelaxed:
        hypothetical: True
        relaxed: False
        relaxed_dataset: "oqmd_relaxed"
        structures_file: "inputs/oqmd-structures/oqmdv1_4-unrelaxed-structures.json.gz"
        relaxed_energies: "inputs/oqmd-structures/oqmdv1_4-relaxed-energies.csv"
    oqmd_relaxed:
        hypothetical: True
        relaxed: True
        structures_file: "inputs/oqmd-structures/oqmdv1_4-relaxed-structures.json.gz"
        relaxed_energies: "inputs/oqmd-structures/oqmdv1_4-relaxed-energies.csv"

# structure of outputs:
# <output_dir>/
#   <dataset_name>/
#     <evaluation>_<seed>/
#       train/valid/test splits 
#       <hyperparameters>/
#         trained model
output_dir: "outputs"

# Eval_settings:
# Holdout strategy: 
#    *random_subset* (randsub): leave out a random subset of the structures. Currently hardcoded at 5% for test, 5% for valid
#    *leave_out_comp* (loc): for each composition type, select a composition of the given type 
#         and leave out all of its structures/decorations 
#    *leave_out_comp_minus_one* (loc-1): same as above, but keep a single structure for the left-out composition
# *[icsd/hypo]_lattice*: lattice to use for structures when training and testing
#     *orig*: original lattice
#     *cubic*: transform to a cubic lattice
#     *orig_and_cubic*: use both the original and cubic lattice
# *seed*: random seed to use for train/valid/test splits
# Note that multiple options may be specified and all combinations will be run
#     The example below will run 10 experiments
#     e.g., hypo: [random_subset: 0.05, "leave_out_comp"]
#     e.g., seed: [1,2,3,4,5]
experiments:

    #- datasets: ["icsd", "oqmd_unrelaxed"]
    - datasets: ["oqmd_unrelaxed"]
      eval_settings:
          hypo_lattice: ['orig', 'cubic']
          hypo: [random_subset: 0.25]
          # TODO I need to add the comp_type to the eV/atom csv first
          #hypo: ["leave_out_comp"]
          # random seed to use for train/valid/test splits
          #seed: [1,2,3]
          seed: [1]


hyperparameters:
    # some useful tips for selecting these parameter values:
    # https://stackoverflow.com/a/49924566/7483950
    learning_rate: 1E-4
    # number times that the learning algorithm will work through the entire training dataset
    epochs: 100

    # Here, we have to add the prediction target padding onto the input padding
    batch_size: 64   # typical batch sizes= 32, 64, 128, 256 (usually batch size=32 or 64 is optimum)
    max_sites: 256
    max_bonds: 2048

    # model_params
    embed_dimension: 256   # typical embedding dimensions= 32, 64, 128, 256
    num_messages: 6        # typical number of message passing blocks= 3-6
